---
- name: playbook to install a k8s cluster with rke and deploy Rancher Control Plane
  hosts: rke_rancher_clusters
  become: yes
  become_user: root
  gather_facts: no
  roles:
    - role: rke_rancher_clusters
