---

docker_version: 19.03.9
docker_url: "https://download.docker.com/linux/static/stable/x86_64/docker-{{ docker_version }}.tgz"
docker_dest: /usr/bin

### Helm Settings
helm_binary_version: v3.6.3
helm_binary_download_url: "https://get.helm.sh/helm-{{ helm_binary_version }}-linux-amd64.tar.gz"
helm_binary: "./helm"
helm_home: ".helm"
helm_rancher_repo: rancher-stable
helm_rancher_repo_url: "https://releases.rancher.com/server-charts/stable"
helm_rancher_version: "v2.6.0"
helm_binary_dest: /usr/local/bin/helm
# You only need to configure these "helm_certmanager_*" values if you enable
# Let's Encrypt support in the "Rancher Cluster Settings" section!
helm_certmanager_version: 1.5.1
helm_certmanager_jetstack_repo: jetstack
helm_certmanager_jetstack_repo_url: https://charts.jetstack.io

### Kubectl Settings
kubectl_binary_version: v1.21.1
kubectl_binary_download_url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_binary_version }}/bin/linux/amd64/kubectl"
kubectl_binary: "./kubectl-{{ kubectl_binary_version }}"
kubectl_binary_dest: /usr/local/bin/kubectl

### RKE Cluster Settings
rke_binary_version: v1.2.12
rke_binary_download_url: "https://github.com/rancher/rke/releases/download/{{ rke_binary_version }}/rke_linux-amd64"
rke_cluster_bin: "./rke-{{ rke_binary_version }}"

#rke_cluster_kube_config: "kube_config_config-{{ inventory_hostname }}.yml" ##commeneted by sanjoy
#rke_cluster_config: "config-{{ inventory_hostname }}.yml" ##commeneted by sanjoy
rke_cluster_config: "rke_rancher_mgmt_cluster.yaml" ##added by sanjoy
rke_cluster_kube_config: "kube_config_{{ rke_cluster_config }}" ##added by sanjoy


rke_kubernetes_version: v1.20.10-rancher1
rke_ssh_user: sanjoy    # due to https://bugzilla.redhat.com/show_bug.cgi?id=1527565
rke_ssh_agent_auth: true
rke_network_interface: eth0
rke_cluster_group_inventory_name: "{{ groups['rke_' + inventory_hostname] }}"
rke_binary_dest: /usr/local/bin/rke

### Rancher Cluster Settings
# General Rancher Settings
#rancher_hostname: "" ##commented by sanjoy
rancher_hostname: "rancher-lb.tcs.local" ## added by sanjoy


rancher_admin_password: ""
rancher_admin_initial_password: admin
rancher_telemetry: out
## Rancher SSL Configuration
# See https://rancher.com/docs/rancher/v2.x/en/installation/k8s-install/helm-rancher/#4-choose-your-ssl-configuration
# for more information! You have to chose one (and exactly one!) method - disable the others!
#
# If you chose Method 1 or 2, ensure to also enable Cert-Manager (otherwide disable it!):
#rancher_certmanager_enabled: false ##commented by Sanjoy
rancher_certmanager_enabled: true   ## added by sanjoy
#
# Method 1: "Rancher-generated TLS certificate" (fully handled by Rancher via Cert-Manager)
#
#rancher_generated_self_signed_certificates: false ##commented by Sanjoy
rancher_generated_self_signed_certificates: true ## added by sanjoy
#
# Method 2: "Lets Encrypt Configuration" (fully handled by Rancher via Cert-Manager)
#
rancher_lets_encrypt_generated_certificated: false
rancher_letsencrypt_email: me@example.com
rancher_certmanager_crd_url: "https://github.com/jetstack/cert-manager/releases/download/v{{ helm_certmanager_version }}/cert-manager.crds.yaml"
#
# Method 3: "Bring your own certificate" (officially signed or self-signed configuration)
#
#rancher_bring_your_own_certificates: true ##commented by Sanjoy
rancher_bring_your_own_certificates: false ## added by sanjoy
rancher_tls_crt: ""
rancher_tls_key: ""
rancher_tls_cacerts: ""
# rancher_tls_self_signed needs to be true if the Rancher TLS cert is self-signed and not generated by Rancher itself, then also the
# full CA chain needs to be provided via rancher_tls_cacerts. 
# See https://rancher.com/blog/2020/transport-layer-security-p2 for more information
#rancher_tls_self_signed: false ##commented by Sanjoy
rancher_tls_self_signed: true ##added by sanjoy
